import type { SafeFetchResult } from "./fetch.js";
import type { ExtractedPage } from "./html.js";

export interface Observation {
  ruleId: string;
  category: "http" | "technical" | "content" | "performance" | "accessibility" | "security" | "privacy";
  title: string;
  severity: "critical" | "high" | "medium" | "low" | "info";
  confidence: "proven" | "strong_inference" | "hypothesis";
  summary: string;
  inference: string;
  impact: string;
  recommendation: string;
  verification: string;
  evidenceLabel: string;
  evidenceValue: string;
}

export function analyzePage(result: SafeFetchResult, extracted: ExtractedPage): Observation[] {
  const observations: Observation[] = [];
  const add = (observation: Observation) => observations.push(observation);
  if (result.statusCode >= 500) add(rule("http-5xx", "http", "Sunucu hatası yanıtı", "critical", `Final URL HTTP ${result.statusCode} döndürüyor.`, "Arama motorları ve kullanıcılar içeriğe erişemeyebilir.", "Sunucu ve upstream hata kaynağını giderin.", "URL’nin tutarlı biçimde HTTP 200 veya amaçlanan yönlendirmeyi döndürdüğünü doğrulayın.", "HTTP status", String(result.statusCode)));
  else if (result.statusCode >= 400) add(rule("http-4xx", "http", "İstemci hatası yanıtı", "high", `Final URL HTTP ${result.statusCode} döndürüyor.`, "İçerik kullanıcılar ve crawler’lar için erişilemez olabilir.", "URL’nin kaldırılma veya yönlendirme politikasını doğrulayın.", "Beklenen status kodunu ve dahili linkleri yeniden tarayın.", "HTTP status", String(result.statusCode)));
  if (!extracted.title) add(rule("missing-title", "content", "Sayfa başlığı bulunamadı", "high", "HTML5 DOM içinde title öğesi yok.", "Arama sonucu başlığı ve sayfa konusu sinyali zayıflayabilir.", "Benzersiz ve niyetle uyumlu bir title ekleyin.", "Raw ve rendered DOM’da tek, dolu title bulunduğunu doğrulayın.", "DOM selector", "title: not found"));
  else if (extracted.title.length < 15 || extracted.title.length > 65) add(rule("title-length", "content", "Title uzunluğu önerilen aralığın dışında", "low", `Title ${extracted.title.length} karakter: ${extracted.title}`, "Arama motoru title’ı yeniden yazabilir veya konu anlatımı yetersiz kalabilir; kesin piksel kesimi cihaz ve sorguya göre değişir.", "Title’ı benzersiz, doğal ve ana niyeti öne alan biçimde gözden geçirin.", "SERP önizlemesini farklı cihazlarda kontrol edin; kuralı katı sıralama faktörü olarak yorumlamayın.", "Title length", String(extracted.title.length)));
  if (!extracted.description) add(rule("missing-description", "content", "Meta description bulunamadı", "medium", "DOM içinde name=description meta öğesi yok.", "Arama snippet’i üzerindeki mesaj kontrolü azalabilir; bu doğrudan sıralama cezası değildir.", "Sayfaya özgü açıklayıcı bir description ekleyin.", "DOM’da dolu bir meta description bulunduğunu doğrulayın.", "DOM selector", "meta[name=description]: not found"));
  else if (extracted.description.length < 50 || extracted.description.length > 170) add(rule("description-length", "content", "Meta description uzunluğu dikkat gerektiriyor", "low", `Description ${extracted.description.length} karakter.`, "Snippet mesajı eksik kalabilir veya arama motoru tarafından farklı gösterilebilir; bu doğrudan sıralama faktörü değildir.", "Arama niyetini ve sayfanın ayırt edici değerini doğal bir metinle anlatın.", "Gerçek SERP örneklerini sorgu ve cihaz bazında gözden geçirin.", "Description length", String(extracted.description.length)));
  if (extracted.canonicalUrls.length === 0 && result.statusCode === 200) add(rule("missing-canonical", "technical", "Canonical bildirimi bulunamadı", "medium", "HTML içinde rel=canonical gözlenmedi.", "Benzer URL varyantlarında tercih sinyalinin kontrolü azalabilir; Google yine kendi canonical’ını seçebilir.", "İndekslenebilir sayfaya mutlak ve kendisiyle tutarlı canonical ekleyin.", "HTML, HTTP Link header ve yönlendirme sonrası final URL’yi birlikte doğrulayın.", "DOM selector", "link[rel~=canonical]: not found"));
  if (extracted.canonicalUrls.length > 1) add(rule("multiple-canonical", "technical", "Birden fazla canonical bulundu", "high", `${extracted.canonicalUrls.length} canonical adayı gözlendi.`, "Çelişkili canonical sinyalleri tercih edilen URL yorumunu zayıflatabilir.", "Tek bir tutarlı canonical bırakın.", "HTML ve HTTP Link header’da tek canonical hedefi doğrulayın.", "Canonical values", extracted.canonicalUrls.join("\n")));
  if (extracted.canonicalUrls.length === 1) { try { const canonical = new URL(extracted.canonicalUrls[0]!, result.finalUrl); if (canonical.origin !== new URL(result.finalUrl).origin) add(rule("cross-origin-canonical", "technical", "Canonical farklı bir domaine işaret ediyor", "high", `Canonical hedefi: ${canonical.toString()}`, "Yanlış yapılandırılmışsa sayfanın indeks sinyalleri başka bir domaine aktarılabilir.", "Hedefin bilinçli olduğunu doğrulayın; değilse aynı içerikteki tercih edilen URL’ye düzeltin.", "Final URL ve canonical kaynağını yeniden tarayın, ardından indeks sonucunu GSC erişimi varsa ayrıca kontrol edin.", "Canonical URL", canonical.toString())); } catch { add(rule("invalid-canonical", "technical", "Canonical URL geçersiz", "high", `Ayrıştırılamayan canonical: ${extracted.canonicalUrls[0]}`, "Crawler’lar canonical sinyalini yok sayabilir.", "Geçerli mutlak HTTP(S) URL kullanın.", "URL ayrıştırma ve yeniden crawl ile doğrulayın.", "Canonical value", extracted.canonicalUrls[0]!)); } }
  if (!extracted.language) add(rule("missing-html-lang", "accessibility", "Doküman dili belirtilmemiş", "medium", "HTML kök öğesinde lang niteliği yok.", "Ekran okuyucular doğru telaffuz dilini seçemeyebilir.", "Geçerli BCP 47 dil etiketi ekleyin.", "HTML kök öğesindeki lang değerini doğrulayın.", "DOM selector", "html[lang]: not found"));
  if (extracted.h1.length === 0) add(rule("missing-h1", "content", "Görünür ana başlık bulunamadı", "medium", "DOM içinde H1 öğesi yok.", "Sayfanın görünür ana konusu kullanıcılar için belirsiz olabilir.", "Sayfanın ana konusunu anlatan görünür bir başlık ekleyin.", "Başlık hiyerarşisini manuel ve otomatik olarak yeniden kontrol edin.", "H1 count", "0"));
  if (extracted.h1.length > 1) add(rule("multiple-h1", "content", "Birden fazla H1 gözlendi", "low", `${extracted.h1.length} H1 bulundu: ${extracted.h1.slice(0, 5).join(" | ")}`, "HTML5 birden fazla H1’e izin verse de görsel ve anlamsal hiyerarşi belirsiz olabilir.", "Her H1’in gerçekten bölüm veya sayfa ana başlığı olup olmadığını erişilebilirlik ağacında doğrulayın.", "Manuel başlık hiyerarşisi incelemesi yapın; bunu tek başına SEO hatası saymayın.", "H1 count", String(extracted.h1.length)));
  if (!extracted.viewport) add(rule("missing-viewport", "performance", "Mobil viewport bildirimi bulunamadı", "high", "meta[name=viewport] öğesi gözlenmedi.", "Mobil tarayıcılarda sayfa masaüstü genişliğinde ölçeklenebilir ve kullanılabilirlik düşebilir.", "Responsive tasarıma uygun viewport bildirimi ekleyin.", "Gerçek mobil cihaz ve responsive testte görünümü doğrulayın.", "DOM selector", "meta[name=viewport]: not found"));
  if (extracted.imagesMissingAlt > 0) add(rule("image-alt-missing", "accessibility", "Bazı görsellerde alt niteliği yok", "medium", `${extracted.imageCount} görselin ${extracted.imagesMissingAlt} tanesinde alt niteliği bulunmadı.`, "Ekran okuyucu kullanıcıları görselin anlamına erişemeyebilir.", "Anlamlı görsellere bağlamsal alt metin; dekoratif görsellere boş alt niteliği ekleyin.", "axe ve manuel ekran okuyucu testiyle her görselin amacını doğrulayın.", "Images without alt attribute", String(extracted.imagesMissingAlt)));
  if (extracted.invalidStructuredDataBlocks > 0) add(rule("invalid-json-ld", "technical", "Geçersiz JSON-LD bloğu bulundu", "high", `${extracted.invalidStructuredDataBlocks}/${extracted.structuredDataBlocks} JSON-LD bloğu JSON olarak ayrıştırılamadı.`, "Yapılandırılmış veri işlenmeyebilir; uygunluk ayrıca schema ve Google politika doğrulaması gerektirir.", "JSON sözdizimini düzeltin ve kullanılan schema türünün gerekli alanlarını inceleyin.", "Schema validator ve Rich Results Test ile yeniden doğrulayın.", "Invalid JSON-LD blocks", String(extracted.invalidStructuredDataBlocks)));
  if (extracted.robotsDirectives.includes("noindex")) add(rule("noindex-observed", "technical", "Noindex direktifi gözlendi", "info", "Meta robots/googlebot içinde noindex bulundu.", "Arama motorları bu URL’yi indeks dışında tutabilir; bunun kasıtlı olup olmadığı bilinmiyor.", "Sayfanın indeks politikasını içerik sahibiyle doğrulayın.", "Meta robots ve X-Robots-Tag header’ı birlikte yeniden kontrol edin.", "Robots directives", extracted.robotsDirectives.join(", ")));
  const securityHeaders = ["content-security-policy", "x-content-type-options", "referrer-policy"];
  const missingHeaders = securityHeaders.filter((header) => !result.headers[header]);
  if (missingHeaders.length > 0) add(rule("security-header-observation", "security", "Bazı güvenlik header’ları gözlenmedi", "low", `Yanıtta şu header’lar gözlenmedi: ${missingHeaders.join(", ")}.`, "Etki uygulama bağlamına ve mevcut diğer kontrollere bağlıdır.", "Header gerekliliğini uygulama bağlamında değerlendirin ve politikayı test edin.", "Yalnızca varlığı değil header değerlerini ve browser davranışını doğrulayın.", "Missing response headers", missingHeaders.join(", ")));
  return observations;
}

function rule(ruleId: string, category: Observation["category"], title: string, severity: Observation["severity"], summary: string, impact: string, recommendation: string, verification: string, evidenceLabel: string, evidenceValue: string): Observation {
  return { ruleId, category, title, severity, confidence: "proven", summary, inference: "Teknik durum doğrudan gözlendi; sıralama, trafik, dönüşüm veya nedensel iş etkisi harici erişimle doğrulanamaz.", impact, recommendation, verification, evidenceLabel, evidenceValue };
}
