import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, BadgeCheck, Bot, ChevronRight, CircleDot, Clock3, ExternalLink, Eye, FlaskConical, Globe2, Leaf, LoaderCircle, LockKeyhole, Play, Plus, Route, ShieldCheck, Sparkles, Target } from "lucide-react";
import type { IntelligenceItem, IntelligenceModule, JourneyDefinition, JourneyRun, SiteEvent, SiteSummary } from "@evidera/contracts";
import { api } from "../lib/api";

const moduleMeta: Array<{ id: IntelligenceModule | "all"; label: string; icon: typeof Activity }> = [
  { id: "all", label: "Tümü", icon: Sparkles }, { id: "change", label: "Değişim", icon: Clock3 }, { id: "content", label: "İçerik", icon: Target },
  { id: "structured_data", label: "Schema", icon: Globe2 }, { id: "performance", label: "Performance", icon: Activity }, { id: "accessibility", label: "Accessibility", icon: Eye },
  { id: "privacy", label: "Privacy", icon: LockKeyhole }, { id: "trust", label: "Trust", icon: ShieldCheck }, { id: "ads", label: "Ads", icon: Target },
  { id: "compatibility", label: "Compatibility", icon: Globe2 }, { id: "sustainability", label: "Sustainability", icon: Leaf }, { id: "ai_visibility", label: "AI visibility", icon: Bot },
];

export function IntelligenceCenterPage({ activeSite }: { activeSite: SiteSummary }) {
  const [items, setItems] = useState<IntelligenceItem[]>([]); const [events, setEvents] = useState<SiteEvent[]>([]); const [module, setModule] = useState<IntelligenceModule | "all">("all"); const [view, setView] = useState<"opportunities" | "timeline">("opportunities"); const [selected, setSelected] = useState<IntelligenceItem | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const [nextItems, nextEvents] = await Promise.all([api.intelligence(activeSite.id), api.events(activeSite.id)]); setItems(nextItems); setEvents(nextEvents); } finally { setLoading(false); } }, [activeSite.id]);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => module === "all" ? items : items.filter((item) => item.module === module), [items, module]);
  const counts = useMemo(() => new Map(moduleMeta.map((entry) => [entry.id, entry.id === "all" ? items.length : items.filter((item) => item.module === entry.id).length])), [items]);
  const update = async (item: IntelligenceItem, status: "planned" | "implemented" | "dismissed") => { await api.updateIntelligence(item.id, status); setItems((current) => current.filter((entry) => entry.id !== item.id)); setSelected(null); };
  return <div className="page-stack intelligence-center">
    <section className="page-intro"><div><span className="section-kicker">Sürekli dış gözlem</span><h2>Intelligence Center</h2><p>Değişiklik, fırsat ve deney hipotezlerini kanıt sınırlarıyla birlikte yönetin.</p></div><div className="segmented-control"><button className={view === "opportunities" ? "is-active" : ""} onClick={() => setView("opportunities")}>Fırsatlar</button><button className={view === "timeline" ? "is-active" : ""} onClick={() => setView("timeline")}>Zaman çizgisi</button></div></section>
    <section className="intelligence-kpis"><article className="surface-card"><span>Aktif fırsat</span><strong>{items.length}</strong><small>Kanıt veya test hipotezi</small></article><article className="surface-card"><span>Yüksek öncelik</span><strong>{items.filter((item) => item.priority >= 70).length}</strong><small>70+ öncelik</small></article><article className="surface-card"><span>Son değişiklikler</span><strong>{events.length}</strong><small>En fazla 200 olay</small></article><article className="surface-card"><span>Kanıtlandı</span><strong>{items.filter((item) => item.confidence === "proven").length}</strong><small>Deterministik gözlem</small></article></section>
    {view === "opportunities" ? <div className="intelligence-layout"><aside className="surface-card intelligence-modules">{moduleMeta.map((entry) => <button key={entry.id} className={module === entry.id ? "is-active" : ""} onClick={() => setModule(entry.id)}><entry.icon size={16}/><span>{entry.label}</span><small>{counts.get(entry.id) ?? 0}</small></button>)}</aside><section className="surface-card intelligence-list">{loading ? <div className="empty-state"><LoaderCircle className="spinning"/><strong>Intelligence yükleniyor</strong></div> : filtered.map((item) => <button className={`intelligence-row priority-${item.priority >= 70 ? "high" : item.priority >= 50 ? "medium" : "low"}`} key={item.id} onClick={() => setSelected(item)}><span className="priority-score">{item.priority}</span><div><span className="intelligence-row-meta">{moduleMeta.find((entry) => entry.id === item.module)?.label ?? item.module} · {item.confidence === "proven" ? "Kanıtlandı" : item.confidence === "strong_inference" ? "Güçlü çıkarım" : "Hipotez"}</span><strong>{item.title}</strong><p>{item.observation}</p><small>{item.source} · {new Date(item.lastSeenAt).toLocaleString("tr-TR")}</small></div><ChevronRight size={17}/></button>)}{!loading && filtered.length === 0 && <div className="empty-state"><BadgeCheck size={25}/><strong>Aktif öğe yok</strong><span>Yeni audit ölçümleri bu modüle işlendiğinde burada görünür.</span></div>}</section></div> : <section className="surface-card event-timeline">{events.map((event) => <article key={event.id}><span className={`event-dot severity-${event.severity}`}><CircleDot size={15}/></span><div><small>{new Date(event.capturedAt).toLocaleString("tr-TR")} · {event.kind}</small><strong>{event.title}</strong><p>{event.observation}</p>{event.sourceUrl && <a href={event.sourceUrl} target="_blank" rel="noreferrer">Kaynağı aç <ExternalLink size={13}/></a>}<details><summary>Önce / sonra kanıtı</summary><pre>{JSON.stringify({ before: event.beforeValue, after: event.afterValue }, null, 2)}</pre><p><b>Çıkarım sınırı:</b> {event.inference}</p></details></div></article>)}{events.length === 0 && <div className="empty-state"><Clock3 size={25}/><strong>Henüz olay yok</strong><span>İlk audit taban çizgisini oluşturur; sonraki auditler farkları gösterir.</span></div>}</section>}
    {selected && <div className="intelligence-drawer-backdrop" onMouseDown={(event) => event.target === event.currentTarget && setSelected(null)}><aside className="intelligence-drawer" role="dialog" aria-modal="true" aria-labelledby="intel-title"><button className="modal-close" onClick={() => setSelected(null)} aria-label="Kapat">×</button><span className="section-kicker">{selected.module} · öncelik {selected.priority}</span><h2 id="intel-title">{selected.title}</h2><EvidenceSection label="Gözlem" text={selected.observation}/><EvidenceSection label="Kanıt" text={selected.evidenceSummary}/><EvidenceSection label="Çıkarım sınırı" text={selected.inference}/><EvidenceSection label="Olası etki" text={selected.impact}/><EvidenceSection label="Öneri" text={selected.recommendation}/><EvidenceSection label="Doğrulama" text={selected.verification}/><div className="methodology-note"><FlaskConical size={17}/><div><strong>{selected.source}</strong><span>{selected.methodology}</span></div></div><div className="drawer-actions"><button className="secondary-button" onClick={() => void update(selected, "dismissed")}>Kapat</button><button className="secondary-button" onClick={() => void update(selected, "implemented")}>Uygulandı</button><button className="primary-button" onClick={() => void update(selected, "planned")}>Planla</button></div></aside></div>}
  </div>;
}

function EvidenceSection({ label, text }: { label: string; text: string }) { return <section className="evidence-section"><span>{label}</span><p>{text}</p></section>; }

const presets = [
  { name: "Form görünürlük kontrolü", selector: "form", description: "En az bir formun görünür olduğunu doğrula" },
  { name: "İletişim yolu kontrolü", selector: "a[href^='tel:'],a[href^='mailto:'],a[href*='wa.me'],a[href*='whatsapp']", description: "Doğrudan iletişim bağlantısının görünürlüğünü doğrula" },
  { name: "Birincil CTA kontrolü", selector: "main a,main button", description: "Ana içerikte bir CTA’nın görünürlüğünü doğrula" },
];

export function JourneysPage({ activeSite }: { activeSite: SiteSummary }) {
  type JourneyWithRun = JourneyDefinition & { latestRun: JourneyRun | null };
  const [journeys, setJourneys] = useState<JourneyWithRun[]>([]); const [creating, setCreating] = useState(false); const [busy, setBusy] = useState<string | null>(null); const [form, setForm] = useState({ name: presets[0]!.name, startUrl: activeSite.origin, device: "mobile" as "mobile" | "desktop", selector: presets[0]!.selector, description: presets[0]!.description });
  const load = useCallback(() => api.journeys(activeSite.id).then(setJourneys), [activeSite.id]); useEffect(() => { setForm((value) => ({ ...value, startUrl: activeSite.origin })); void load(); }, [activeSite.origin, load]);
  useEffect(() => { const pending = journeys.some((item) => item.latestRun && ["queued", "running"].includes(item.latestRun.status)); if (!pending) return; const timer = window.setInterval(() => void load(), 1500); return () => window.clearInterval(timer); }, [journeys, load]);
  const create = async () => { await api.createJourney({ siteId: activeSite.id, name: form.name, startUrl: form.startUrl, device: form.device, locale: activeSite.language, steps: [{ action: "assert_visible", selector: form.selector, description: form.description }] }); setCreating(false); await load(); };
  const run = async (journeyId: string) => { setBusy(journeyId); try { await api.runJourney(journeyId); await load(); } finally { setBusy(null); } };
  return <div className="page-stack"><section className="page-intro"><div><span className="section-kicker">No-submit sentetik test</span><h2>Kullanıcı yolculukları</h2><p>Aynı-origin sınırında, gerçek form gönderimi yapmadan kritik adımları ekran görüntüsüyle doğrulayın.</p></div><button className="primary-button" onClick={() => setCreating((value) => !value)}><Plus size={17}/> Yolculuk tanımla</button></section><div className="scan-safety-note"><LockKeyhole size={17}/><span>Submit, password/file alanları, üçüncü taraf navigasyon ve 12 adımdan uzun akışlar worker tarafından engellenir.</span></div>
    {creating && <section className="surface-card journey-builder"><div className="preset-grid">{presets.map((preset) => <button key={preset.name} onClick={() => setForm({ ...form, ...preset })}><Route size={17}/><strong>{preset.name}</strong><small>{preset.description}</small></button>)}</div><label><span>Ad</span><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })}/></label><label><span>Başlangıç URL</span><input type="url" value={form.startUrl} onChange={(event) => setForm({ ...form, startUrl: event.target.value })}/></label><label><span>Doğrulanacak CSS selector</span><input value={form.selector} onChange={(event) => setForm({ ...form, selector: event.target.value })}/></label><div className="panel-actions"><select value={form.device} onChange={(event) => setForm({ ...form, device: event.target.value as "mobile" | "desktop" })}><option value="mobile">Mobil 390 px</option><option value="desktop">Desktop 1440 px</option></select><button className="primary-button" onClick={() => void create()}>Güvenli yolculuğu kaydet</button></div></section>}
    <section className="journey-grid">{journeys.map((journey) => { const steps = Array.isArray(journey.latestRun?.result.steps) ? journey.latestRun.result.steps as Array<Record<string, unknown>> : []; return <article className="surface-card journey-card" key={journey.id}><div className="journey-card-head"><span><Route size={19}/></span><div><strong>{journey.name}</strong><small>{journey.device} · {journey.steps.length} adım</small></div><span className={`run-status ${journey.latestRun?.status ?? "idle"}`}>{journey.latestRun?.status ?? "Hazır"}</span></div><p>{journey.startUrl}</p><ol>{journey.steps.map((step, index) => <li key={index}><span>{index + 1}</span>{step.description}</li>)}</ol>{journey.latestRun?.errorMessage && <div className="scan-error">{journey.latestRun.errorMessage}</div>}{steps.length > 0 && <div className="journey-evidence-strip">{steps.map((step) => <a key={String(step.step)} href={`/api/journey-runs/${journey.latestRun!.id}/artifacts/${String(step.step)}`} target="_blank" rel="noreferrer"><Eye size={14}/> Adım {String(step.step)}</a>)}</div>}<button className="primary-button" disabled={busy === journey.id || journey.latestRun?.status === "running" || journey.latestRun?.status === "queued"} onClick={() => void run(journey.id)}>{busy === journey.id ? <LoaderCircle className="spinning" size={16}/> : <Play size={16}/>} Testi çalıştır</button></article>; })}{journeys.length === 0 && <button className="add-site-card" onClick={() => setCreating(true)}><span><Route size={22}/></span><strong>İlk yolculuğu tanımla</strong><small>Form, iletişim veya CTA görünürlüğünü doğrula</small></button>}</section>
  </div>;
}
